### ISSUE TITLE
Manually specify a tag?

### ISSUE THREAD

**Issue by ThePieMonster** [phish108/autotag-action#195]
Is it possible to manually specify a tag using something like:

```
      - name: Auto Tag
        uses: phish108/autotag-action@v1.1.64
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          version: "${{ steps.id.outputs.version }}"

```
